// <auto-generated />
using System;
using EShop.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EShop.Model.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20210309143334_removedNumber")]
    partial class removedNumber
    {
     
    }
}
